# Generated by Django 3.1.2 on 2022-02-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220217_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='region',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='state',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
