# Generated by Django 3.1.2 on 2022-02-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220217_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
