# Generated by Django 4.0.3 on 2022-11-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoresModel',
        ),
    ]
