# Generated by Django 4.0.3 on 2022-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_menulist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_shipped',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
