# Generated by Django 4.1.4 on 2023-04-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_category_id_alter_menulist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='caut',
            field=models.BooleanField(default=False),
        ),
    ]
