# Generated by Django 4.1.4 on 2023-04-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_ordermodel_caut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='caut',
        ),
    ]
