# Generated by Django 4.1.4 on 2023-04-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_yenulist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yenulist',
            new_name='yenulists',
        ),
    ]
