# Generated by Django 4.1.4 on 2023-04-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_rename_yenulist_yenulists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yenulists',
        ),
    ]
