# Generated by Django 4.1.4 on 2023-04-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_yenulist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yenulist',
        ),
    ]
