# Generated by Django 4.1.4 on 2023-04-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_delete_yenulist'),
    ]

    operations = [
        migrations.CreateModel(
            name='yenulist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
